/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ders09Lab;

import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fsmblm0
 */
public class Ornek1 extends javax.swing.JFrame {

    DefaultListModel dlm = new DefaultListModel();
    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form Soru2
     */
    public Ornek1() {
        initComponents();
        dtm.setColumnIdentifiers(new Object[]{"F_ID", "M_ID", "U_ID", "Tutar", "Miktar"});
        listMusteri.setModel(dlm);
        tbl_fatura.setModel(dtm);
        cmb_fiyat.addItem("buyuk");
        cmb_fiyat.addItem("kucuk");
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM MUSTERI");
            // listeye müşteri ekleme
            while (rs.next()) {
                dlm.addElement(rs.getInt("M_ID") + " " + rs.getString("ADI"));
            }
            //cmbBox a ürün ekleme
            rs = stmt.executeQuery("SELECT * FROM URUN");

            while (rs.next()) {
                cmb_urunler.addItem(rs.getString("URUN_ID"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(Ornek1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmb_urunler = new javax.swing.JComboBox<>();
        btn_sorgu_2b = new javax.swing.JButton();
        btn_toplamYaz2c = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMusteri = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmb_fiyat = new javax.swing.JComboBox<>();
        txt_fiyat = new javax.swing.JTextField();
        btn_faturaEkle_3a = new javax.swing.JButton();
        btn_faturaSil_3c = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_fatura = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün");

        btn_sorgu_2b.setText("Sorgu_2b");
        btn_sorgu_2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sorgu_2bActionPerformed(evt);
            }
        });

        btn_toplamYaz2c.setText("Toplam_Yaz_2c");
        btn_toplamYaz2c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplamYaz2cActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listMusteri);

        jLabel2.setText("Müşteri");

        jLabel3.setText("Fiyat");

        btn_faturaEkle_3a.setText("Fatura_Ekle_3ab");
        btn_faturaEkle_3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_faturaEkle_3aActionPerformed(evt);
            }
        });

        btn_faturaSil_3c.setText("Fatura_Sil_3c");
        btn_faturaSil_3c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_faturaSil_3cActionPerformed(evt);
            }
        });

        tbl_fatura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_fatura);

        jLabel4.setText("Fatura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(28, 28, 28)
                                    .addComponent(cmb_urunler, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_sorgu_2b, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_faturaEkle_3a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_toplamYaz2c, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_faturaSil_3c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_urunler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sorgu_2b)
                    .addComponent(btn_toplamYaz2c))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(cmb_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_faturaEkle_3a)
                            .addComponent(btn_faturaSil_3c))))
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sorgu_2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sorgu_2bActionPerformed
        if (listMusteri.getSelectedIndex() != -1 && !txt_fiyat.getText().isEmpty()) {
            int secilenId = 0;
            if (cmb_fiyat.getSelectedItem() == "buyuk") {
                Connection con;
                try {
                    con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
                    Statement stmt = con.createStatement();

                    //secilenMusteriId
                    int musteriId=Integer.parseInt(listMusteri.getSelectedValue().split(" ")[0]);
                    ResultSet rs = stmt.executeQuery("SELECT * FROM MUSTERI WHERE M_ID =" + musteriId);
                    if (rs.next()) {
                        secilenId = (int) rs.getInt("M_ID");
                    }

                    // tabloya ekleme
                    if (cmb_fiyat.getSelectedItem().equals("buyuk")){
                        System.out.println("SELECT * FROM FATURA WHERE M_ID = " + secilenId + " AND fiyat >"+txt_fiyat.getText());
                        rs = stmt.executeQuery("SELECT * FROM FATURA WHERE M_ID = " + secilenId + " AND fiyat >"+txt_fiyat.getText() );
                    }else{
                        System.out.println("SELECT * FROM FATURA WHERE M_ID = " + secilenId + " AND fiyat >"+txt_fiyat.getText());
                        rs = stmt.executeQuery("SELECT * FROM FATURA WHERE M_ID = " + secilenId + " AND fiyat <"+txt_fiyat.getText() );
                    }
                    
                    
                    dtm.setRowCount(0);
                    while (rs.next()) {
                        
                        dtm.addRow(new Object[]{rs.getInt("F_ID"), rs.getInt("M_ID"), rs.getString("U_ID"), rs.getInt("fiyat"), rs.getInt("ADET")});
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Ornek1.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {

            }
        }
    }//GEN-LAST:event_btn_sorgu_2bActionPerformed

    private void btn_toplamYaz2cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplamYaz2cActionPerformed
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement stUrun = con.createStatement();

            ResultSet rs1 = stUrun.executeQuery("SELECT * FROM URUN");
            while (rs1.next()) {
                Statement stFatura = con.createStatement();
                ResultSet rs2 = stFatura.executeQuery("SELECT * FROM FATURA WHERE U_ID ='" + rs1.getString("URUN_ID")+"'");
                int toplam=0;
                while (rs2.next()) {
                    toplam+=rs2.getInt("adet");
                }
                Statement stUrunUpdate = con.createStatement();
                stUrunUpdate.executeUpdate("UPDATE URUN SET TOPLAM_ADET = " + toplam + " WHERE URUN_ID ='" + rs1.getString("URUN_ID")+"'");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Ornek1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_toplamYaz2cActionPerformed

    private void btn_faturaEkle_3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_faturaEkle_3aActionPerformed
        
    }//GEN-LAST:event_btn_faturaEkle_3aActionPerformed

    private void btn_faturaSil_3cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_faturaSil_3cActionPerformed
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_btn_faturaSil_3cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ornek1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ornek1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ornek1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ornek1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ornek1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_faturaEkle_3a;
    private javax.swing.JButton btn_faturaSil_3c;
    private javax.swing.JButton btn_sorgu_2b;
    private javax.swing.JButton btn_toplamYaz2c;
    private javax.swing.JComboBox<String> cmb_fiyat;
    private javax.swing.JComboBox<String> cmb_urunler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listMusteri;
    private javax.swing.JTable tbl_fatura;
    private javax.swing.JTextField txt_fiyat;
    // End of variables declaration//GEN-END:variables
}
